# Generated by Django 5.2.7 on 2025-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='page_type',
            field=models.CharField(choices=[('about', 'About Us'), ('contact', 'Contact Us'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('california_privacy', 'California Privacy'), ('disclosure', 'Advertiser Disclosure'), ('team', 'Insurance Panda Team'), ('how_to_use', 'How to Use Insurance Panda'), ('high_risk_auto_insurance', 'High-Risk Auto Insurance')], max_length=50, unique=True),
        ),
    ]
