# Generated by Django 5.2.7 on 2025-11-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_seed_high_risk_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='navbar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
