# Generated by Django 5.2.7 on 2025-11-03 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_companyinfo_footer_logo_companyinfo_navbar_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInsuranceQuotesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Car Insurance Quotes', max_length=200)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('intro_paragraphs', models.JSONField(blank=True, default=list)),
                ('takeaways', models.JSONField(blank=True, default=list)),
                ('state_insurance_data', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('author_bio', models.TextField(blank=True)),
                ('author_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car Insurance Quotes Page',
                'verbose_name_plural': 'Car Insurance Quotes Pages',
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={},
        ),
    ]
