# Generated by Django 5.2.7 on 2025-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_carinsurancequotespage_alter_companyinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'ordering': ['-is_active', '-updated_at'], 'verbose_name': 'Company Information', 'verbose_name_plural': 'Company Information'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one company info can be active at a time'),
        ),
    ]
