# Generated by Django 5.2.7 on 2025-11-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_companyinfo_options_companyinfo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='meta_image',
            field=models.ImageField(blank=True, help_text='Image used for social sharing (Open Graph/Twitter)', null=True, upload_to='site/'),
        ),
    ]
