# Generated by Django 5.2.7 on 2025-11-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_companyinfo_meta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='footer_logo_alt',
            field=models.CharField(blank=True, help_text='Alt text for footer logo', max_length=120),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='meta_image_alt',
            field=models.CharField(blank=True, help_text='Alt text/description for social sharing image', max_length=120),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='navbar_logo_alt',
            field=models.CharField(blank=True, help_text='Alt text for navbar logo', max_length=120),
        ),
    ]
