# Generated by Django 5.2.7 on 2025-11-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_staticpage_menu_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenuPage',
            fields=[
            ],
            options={
                'verbose_name': 'Company Menu Page',
                'verbose_name_plural': 'Company Menu Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.staticpage',),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Custom link text for menus; defaults to title', max_length=100),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='nav_group',
            field=models.CharField(blank=True, default='Company', help_text='Header menu group name for dropdown (e.g., Company)', max_length=50),
        ),
    ]
