# Generated by Django 5.2.7 on 2025-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_footermenupage_alter_staticpage_menu_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Main site favicon (ICO/PNG)', null=True, upload_to='site/'),
        ),
    ]
