# Generated by Django 5.2.7 on 2025-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_companyinfo_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='footer_disclaimer',
            field=models.TextField(blank=True, help_text='Footer disclaimer text shown at the bottom of the site'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='page_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
