# Generated by Django 5.2.7 on 2025-11-07 12:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_companyinfo_footer_disclaimer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinsurancequotespage',
            name='body_html',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='carinsurancequotespage',
            name='toc_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='carinsurancequotespage',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
