# Generated by Django 5.2.7 on 2025-11-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_carinsurancequotespage_body_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinsurancequotespage',
            name='author_image_url',
        ),
        migrations.AddField(
            model_name='carinsurancequotespage',
            name='author_context',
            field=models.CharField(choices=[('detail', 'Detail Page'), ('blog', 'Blog'), ('faq', 'FAQ'), ('content', 'Content Page')], default='detail', max_length=20),
        ),
        migrations.AddField(
            model_name='carinsurancequotespage',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='authors/'),
        ),
    ]
