# Generated by Django 5.2.7 on 2025-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_carinsurancequotespage_author_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinsurancequotespage',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='carinsurancequotespage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carinsurancequotespage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
