# Generated by Django 5.2.7 on 2025-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_insurancecompany_delete_companypage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='high_risk_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='is_high_risk_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
