# Generated by Django 5.2.7 on 2025-11-02 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_insurancecompany_high_risk_blurb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighRiskInsuranceCompany',
            fields=[
            ],
            options={
                'verbose_name': 'High-Risk Insurance Company',
                'verbose_name_plural': 'High-Risk Insurance Companies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('company.insurancecompany',),
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='company.insurancecompany')),
            ],
            options={
                'verbose_name': 'Company Review',
                'verbose_name_plural': 'Company Reviews',
                'ordering': ['-published_at'],
            },
        ),
    ]
