# Generated by Django 5.2.7 on 2025-11-02 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_highriskinsurancecompany_companyreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
