# Generated by Django 5.2.7 on 2025-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
