# Generated by Django 5.0.7 on 2025-10-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('main', 'Main Category'), ('sub', 'Sub Category'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
