# Generated by Django 5.0.7 on 2025-10-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_parent_category_type_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('main', 'Main Category'), ('sub', 'Sub Category'), ('faq', 'FAQ Category'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
