# Generated by Django 5.2.7 on 2025-11-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('main', 'Main Category'), ('sub', 'Sub Category'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='BlogFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Feedback',
                'verbose_name_plural': 'Blog Feedback',
                'unique_together': {('blog_post', 'ip_address')},
            },
        ),
    ]
