# Generated by Django 5.2.7 on 2025-11-01 16:02

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category__order', 'order', '-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='summary',
        ),
        migrations.AddField(
            model_name='faq',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='faq',
            name='short_answer',
            field=models.TextField(blank=True, help_text='Brief answer for listings', max_length=300),
        ),
        migrations.AddField(
            model_name='faq',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="CSS class for icon (e.g., 'fas fa-car')", max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured FAQs'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
        migrations.CreateModel(
            name='FAQFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='faq.faq')),
            ],
            options={
                'verbose_name': 'FAQ Feedback',
                'verbose_name_plural': 'FAQ Feedback',
                'unique_together': {('faq', 'ip_address')},
            },
        ),
    ]
