# Generated by Django 5.2.7 on 2025-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_options_remove_faq_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
