# Generated by Django 5.2.7 on 2025-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_author_bio_faq_author_image_faq_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='faq',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
